# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:            Hillside Projects
email:            info@hillsideprojects.se
description:      A research/production group formed by Emily Mennerdahl and Jonas Böttern.
baseurl:          '' # The subpath of your site, e.g. /blog
url:              'https://hillsideprojects.se' # The base hostname & protocol for your site
facebook_username: HillsideProjects
vimeo_username:   user31098743

markdown:  kramdown
permalink: /:title.html
paginate:  24
sass:
  style: compressed

plugins: [jekyll-paginate, jekyll/tagging]

include:
  - _pages

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

# Authors
authors:
  hillsideprojects:
    name:             Hillside Projects
    bio:              A research/production group formed by Emily Mennerdahl and Jonas Böttern. Hillside Projects are based in Stockholm, Sweden. Their studio is located in Hagsätra. Hillside Projects are members of <a href="http://idigalleri.org/" target="blank">ID:I Galleri</a> in Stockholm.
    gravatar:         https://s.gravatar.com/avatar/f83141edd9e6339e678648596a403fd5?s=150
    email:            info@hillsideprojects.se
    website:          https://hillsideprojects.se
    facebook_username: HillsideProjects
    vimeo_username:   user31098743
